### PR TITLE
Add RWKV example

### PR DESCRIPTION
**Pull request by Nintorac**

### CODE REVIEW

**Comment by lhenault** [comment]
I've a complicated relationship with conda these days, so if you want an "Anaconda free" `Dockerfile` you can look at my latest changes to other examples to use Python3.9+ [here](https://github.com/lhenault/simpleAI/blob/main/examples/sentence-transformers/Dockerfile). Otherwise LGTM, happy to finally merge :)

**Comment by cahya-wirawan** [comment]
@Nintorac what is the difference between chat and complete function in lib_raven.py?

**Comment by cahya-wirawan** [comment]
In the chat code at BlinkDL/RWKV-LM, there is a check where it will stop to generate text after it sees double new line "\n\n", would you also implement it? or will you prefer to check the "Bob:" to stop the generation instead of "\n\n", since there is possibility that the generated text could include "\n\n" without followed by "Bob:" for example if I ask the chat bot to write code, it will generate "\n\n" before any code.

**Comment by Nintorac** [comment]
> @Nintorac what is the difference between chat and complete function in lib_raven.py?

nothing apparently :sweat: 

> In the chat code at BlinkDL/RWKV-LM, there is a check where it will stop to generate text after it sees double new line "\n\n", would you also implement it? or will you prefer to check the "Bob:" to stop the generation instead of "\n\n", since there is possibility that the generated text could include "\n\n" without followed by "Bob:" for example if I ask the chat bot to write code, it will generate "\n\n" before any code.

No, won't implement that. The OpenAI API has a stop words argument which I had a go at implementing. I had it working locally and was going to upstream to chatrwkv repo but work has picked up so lost that thread for now

**Comment by Nintorac** [comment]
@cahya-wirawan got motivated and finished off the stop words code see here - https://github.com/BlinkDL/ChatRWKV/pull/106

**Comment by cahya-wirawan** [comment]
@Nintorac have you tried the embedding function and tested if it create similar vector for two similar sentences?

**Comment by Nintorac** [comment]
> @Nintorac have you tried the embedding function and tested if it create similar vector for two similar sentences?

Have been working towards this but no luck so far. The langchain QA chain uses deprecated openai endpoints and simpleAI does not implement them. 

Currently

**Comment by cahya-wirawan** [comment]
> Working on batched inference (and generations) at the moment as I thought it would be more widely beneficial and didn't want to have build the vector store one by one

Yes, I am wondering about following code, why context is created from a list of inputs, but at the end only the first one is used:
```
    context = [pipeline.encode(ctx)[-ctx_limit:] for ctx in inputs]
    _, state = model.forward(context[0], None)
```

**Comment by Nintorac** [comment]
Closing in favour of https://github.com/Nintorac/simple_rwkv :)

> Yes, I am wondering about following code, why context is created from a list of inputs, but at the end only the first one is used:

premature optimisation ><

Parallel can work now though https://github.com/BlinkDL/ChatRWKV/pull/113

**Comment by lhenault** [comment]
> Closing in favour of https://github.com/Nintorac/simple_rwkv :)

I should have been faster reviewing and merging this PR I guess, but won't hold a grudge. Solid work still, gave it its first star :)

**Comment by cahya-wirawan** [comment]
> > Closing in favour of https://github.com/Nintorac/simple_rwkv :)
> 
> I should have been faster reviewing and merging this PR I guess, but won't hold a grudge. Solid work still, gave it its first star :)
You could still reopen the PR and merge it if you like and @Nintorac agree with it I guess :-)

**Comment by Nintorac** [comment]
Yea, no problem to still merging it I tried to leave it in a good state here. My plans just got bigger!

**Pull request closed without merging**
